version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: ani_postgres
    restart: always
    environment:
      POSTGRES_USER: aniuser
      POSTGRES_PASSWORD: anipass
      POSTGRES_DB: anidb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
