name: CI
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres: { image: postgres:15, env: { POSTGRES_PASSWORD: postgres }, ports: ['5432:5432'] }
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with: node-version: 20
      - run: npm ci
        working-directory: frontend
      - run: npm ci
        working-directory: backend
      - name: Run backend tests
        run: npm test
        working-directory: backend
      - name: Run frontend lint
        run: npm run lint
        working-directory: frontend
      - name: Build frontend
        run: npm run build
        working-directory: frontend
